name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.5"
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
